### ISSUE TITLE
Read only command in README is incorrect

### ISSUE THREAD

**Issue by bobbywatson3** [emc-openstack/vnxe-cinder-driver#1]
The read-only commands below are incorrect:

> cinder --os-username admin --os-tenant-name admin metadata <volume> set 'attached_mode'='ro'
> cinder --os-username admin --os-tenant-name admin metadata <volume> set 'readonly'='True'

These commands will set the metadata to ro, but as soon as the volume is attached, it's set back to rw. The correct command is:

> cinder readonly-mode-update <cinder volume id> True

This needs to be updated in the OpenStack Juno documentation as well.

**Comment by Jeegn-Chen** [comment]
Thanks a lot for pointing that out!
The README is updated and Gerrit Review is also published to update OpenStack doc

**Comment by Jeegn-Chen** [comment]
Link to Gerrit Review https://review.openstack.org/148493
